submissions-prototype/Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

namespace submissionsprototype.Models
{
    public class AppDbContext : IdentityDbContext<IdentityUser>
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {

        }

        public DbSet<Submission> Submissions { get; set; }

    }
}

submissions-prototype/Models/ErrorViewModel.cs
using System;

namespace submissions_prototype.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

submissions-prototype/Models/ISubmissionRepository.cs
using System;
using System.Collections.Generic;

namespace submissionsprototype.Models
{
    public interface ISubmissionRepository
    {
        IEnumerable<Submission> Submissions { get;  }

        void CreateSubmission(Submission submission);

    }
}

submissions-prototype/Models/Submission.cs
using System;
namespace submissionsprototype.Models
{
    public class Submission
    {
        public Submission()
        {
        }

        public int SubmissionId { get; set; }
        public string SubmissionTitle { get; set; }

    }
}

submissions-prototype/Models/SubmissionMockRepository.cs
using System;
using System.Collections.Generic;

namespace submissionsprototype.Models
{
    public class SubmissionMockRepository : ISubmissionRepository
    {
        public SubmissionMockRepository()
        {
        }

        public IEnumerable<Submission> Submissions
        {

            get
            {

                return new List<Submission> {

                    new Submission { SubmissionId=1, SubmissionTitle="The First Submission"},
                    new Submission { SubmissionId=2, SubmissionTitle="The Second Submission"}



                };


            }

        }

        public void CreateSubmission(Submission submission) {

            //do nothing in mock
        }

    }
}

submissions-prototype/Models/SubmissionRepository.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace submissionsprototype.Models
{
    public class SubmissionRepository : ISubmissionRepository
    {
        private readonly AppDbContext _appDbContext;

        public SubmissionRepository(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        public IEnumerable<Submission> Submissions {

            get
            {

                return _appDbContext.Submissions;

            }

        }

        public void CreateSubmission (Submission submission) {

            _appDbContext.Submissions.Add(submission);

            _appDbContext.SaveChanges();

        }


    }
}

submissions-prototype/ViewModels/SubmissionViewModel.cs
using System;
using System.Collections.Generic;
using submissionsprototype.Models;

namespace submissionsprototype.ViewModels
{
    public class SubmissionViewModel
    {
        public SubmissionViewModel()
        {
        }

        public IEnumerable<Submission> Submissions { get; set; }


    }
}

submissions-prototype/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using submissions_prototype.Models;

namespace submissions_prototype.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

       
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

submissions-prototype/Controllers/SubmissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using submissionsprototype.Models;
using submissionsprototype.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace submissionsprototype.Controllers
{
    public class SubmissionController : Controller
    {

        private readonly ISubmissionRepository _submissionRepository;

        public SubmissionController(ISubmissionRepository submissionRepository) {

            _submissionRepository = submissionRepository;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {

            var submissionViewModel = new SubmissionViewModel
            {

                Submissions = _submissionRepository.Submissions
                                                   
            };

            return View(submissionViewModel);

        }

        public IActionResult Create() {

            return View();

        }

        [HttpPost]
        public IActionResult Create(Submission submission) {

            _submissionRepository.CreateSubmission(submission);

            return RedirectToAction("CreateComplete");

        }

        public IActionResult CreateComplete() {


            return View();

        }
    }
}

submissions-prototype/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


        <h2>Submissions Prototype Home Page</h2>

    

submissions-prototype/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - submissions_prototype</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">submissions_prototype</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Submission" asp-action="Index">View Submissions</a></li>
                    <li><a asp-area="" asp-controller="Submission" asp-action="Create">Create Submissions</a></li>    
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - submissions_prototype</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

submissions-prototype/Views/Submission/Create.cshtml
@model Submission
@{
    ViewData["Title"] = "Create Submissions";
}

<h1>Create A New Submission</h1>

<form asp-action="Create" method="post" class="form-horizontal" role="form">

<div class="form-group">
        <label asp-for="SubmissionTitle" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="SubmissionTitle" class="form-control" />
            <span asp-validation-for="SubmissionTitle" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Create Submission" />
        </div>
    </div>

</form>
    

submissions-prototype/Views/Submission/CreateComplete.cshtml
@model Submission
@{
    ViewData["Title"] = "Submission Created";
 }

 <h1>Submission Created Successfully</h1>

submissions-prototype/Views/Submission/Index.cshtml
@model SubmissionViewModel
@{
    ViewData["Title"] = "View Submissions";
}

<h1>Submissions</h1>

@foreach (var submission in Model.Submissions) {

   <p>@submission.SubmissionId - @submission.SubmissionTitle</p>

}